# Generated by Django 4.2.6 on 2023-12-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_slug_alter_shop_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Shopp',
        ),
    ]
